language: python
python:
  - "2.7"
env: PGVERSION=9.2
dist: trusty
sudo: required
cache: pip
before_install:
 - chmod +x ./bin/travis-build
 - chmod +x ./bin/travis-run
script:
 - ./bin/travis-run-tests
